config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  get '/users/' => 'users#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :diagrams do
    resource :canvas, except: [:edit, :update, :destroy] do
      get :draw
      get :preview
      resources :ideas do
        member do
          put :update_position
        end
      end
    end
  end

end

app/models/canvas.rb
# == Schema Information
#
# Table name: canvas
#
#  id         :bigint           not null, primary key
#  diagram_id :integer
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Canvas < ApplicationRecord
  belongs_to :diagram, class_name: 'Diagram', foreign_key: 'diagram_id'
  has_many :ideas, dependent: :destroy
  # has_one_attached :background

  validates :diagram_id, presence: true


  # def has_background?
  #   self.background.present?
  # end
  #
  # def background
  #   self.image_url
  # end
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController
  before_action :authenticate_user!, except: [:show, :preview]
  before_action :require_edit_permission, only: [:edit, :update, :draw, :destroy]
  before_action :set_diagram

  before_action :allow_iframe_requests, only: [:show, :preview]

  layout "canvas" # except for '#show', '#preview', '#edit' and "#new"

  def index
    @canvases = Canvas.all
  end

  # def new
  #   @canvas = @diagram.build_canvas
  #   respond_to do |format|
  #     format.html { render layout: 'application' }
  #   end
  # end
  #
  # def create
  #   @canvas = @diagram.build_canvas(canvas_params)
  #   if @canvas.save
  #     flash[:notice] = "Canvas created!"
  #     redirect_to(edit_diagram_canvas_path(@diagram))
  #   else
  #     flash[:alert] = "Canvas was not created"
  #     redirect_to(edit_diagram_path(@diagram))
  #   end
  # end

  def show
    @canvas = @diagram.canvas
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def preview
    @canvas = @diagram.canvas
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def draw
    @canvas = @diagram.canvas
  end

  def edit
    @canvas = @diagram.canvas
    respond_to do |format|
      format.html { render layout: 'application' }
    end
  end

  def update
    diagram = Diagram.find_by_id(params[:diagram_id])
    if diagram.canvas.image_url != params[:canvas][:image_url]
      diagram.canvas.update_attribute(:image_url, params[:canvas][:image_url])
    end
    return redirect_to edit_diagram_path(diagram)
  end

  def destroy
    @canvas = @diagram.canvas
    @canvas.destroy
    return redirect_to edit_diagram_path(@diagram)
  end

  private

  def set_diagram
    @diagram = Diagram.find_by_id(params[:diagram_id])
  end

  def canvas_params
    params.require(:canvas).permit(:diagram_id, :image_url)
  end

  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end
end

app/helpers/canvas_helper.rb
module CanvasHelper

  def canvas_actions_list(controller_params)
    if controller_params[:controller] == "canvas"
      case controller_params[:action]
      when "draw"
        return [:show, :preview, :integrate]
      end
    elsif controller_params[:controller] == "diagrams" && controller_params[:action] == "edit"
      diagram = Diagram.find_by_id(params[:id])
      # return (diagram.canvas ? [:show, :edit, :draw, :integrate, :delete] : [:new])
      return (diagram.canvas ? [:show, :preview, :draw, :integrate] : [:new])
    end
    return []
  end
end

app/views/partials/canvas/_actions_buttons.html.erb
<% actions_list ||= canvas_actions_list(params) %>

<%# if actions_list.include?(:edit) %>
  <%#= link_to edit_diagram_canvas_path(diagram), class: "btn btn-xs btn-outline-primary" do %>
<!--    <i class="fas fa-pen-square"></i> Edit Background-->
  <%# end %>
<%# end %>
<% if actions_list.include?(:draw) %>
  <%= link_to draw_diagram_canvas_path(diagram), class: "btn btn-xs btn-outline-secondary" do %>
    <i class="fas fa-pencil-ruler"></i> Draw
  <% end %>
<% end %>

<% if actions_list.include?(:preview) %>
  <%= link_to preview_diagram_canvas_path(diagram), class: "btn btn-xs btn-outline-info", target: "_blank"  do %>
    <i class="fas fa-search"></i> Preview
  <% end %>
<% end %>

<% if actions_list.include?(:show) %>
  <%= link_to diagram_canvas_path(diagram), class: "btn btn-xs btn-outline-primary", target: "_blank" do %>
    <i class="fas fa-eye"></i> View
  <% end %>
<% end %>


<% if actions_list.include?(:integrate) %>
  <%= link_to diagram_canvas_path(diagram),
              data: { target: "#collapseCode", toggle: "collapse"},
              class: "btn btn-xs btn-outline-secondary" do %>
    <i class="fas fa-code"></i> Integrate
  <% end %>
<% end %>


<% if actions_list.include?(:new) %>
  <%= link_to new_diagram_canvas_path(diagram), class: "btn btn-xs btn-outline-primary" do %>
    <i class="far fa-file"></i> Start Canvas
  <% end %>
<% end %>


<div class="collapse" id="collapseCode">
  <div class="card card-body bg-light" style="margin-top:5px;">
    <textarea rows="3" cols="6"><iframe src="<%= Rails.root.join('app', diagram_canvas_path(diagram)) %>>" title="Diagram <%= diagram.name %>"></iframe></textarea>
  </div>
</div>