config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  get '/users/' => 'users#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :diagrams do
    resource :canvas, except: [:edit, :update, :destroy] do
      get :draw
      get :preview
      resources :ideas do
        member do
          put :update_position
        end
      end
    end
  end

end

app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id               :bigint           not null, primary key
#  label            :string
#  background_color :string
#  text_color       :string
#  description      :text
#  canvas_id        :integer
#  url              :string
#  shape_type       :string
#  x_pos            :integer
#  y_pos            :integer
#  width            :float
#  height           :float
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Idea < ApplicationRecord
  belongs_to :canvas, class_name: 'Canvas', foreign_key: 'canvas_id'
  has_one_attached :media
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_canvas_and_diagram
  skip_before_action :verify_authenticity_token

  layout "canvas"

  def index
    @ideas = Idea.where(canvas_id: @canvas)
    render json: @ideas
  end


  def create
    @idea = @canvas.ideas.build(idea_params)
    if @idea.save
      respond_to do |format|
        format.json { render json: @idea }
        format.html {
          flash[:notice] = "Idea created!"
          redirect_to(draw_diagram_canvas_path(@diagram))
        }
      end
    else
      respond_to do |format|
        format.json
        format.html {
          flash[:alert] = "Idea was not created"
          redirect_to(edit_diagram_path(@diagram))
        }
      end
    end
  end

  def edit
    @idea = Idea.find_by_id(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    @idea = Idea.find_by_id(params[:id])
    @idea.update(idea_params)
    redirect_to(draw_diagram_canvas_path(@diagram))
  end

  def update_position
    idea = Idea.find_by_id(params[:id])
    idea.x_pos = params[:idea][:x_pos]
    idea.y_pos = params[:idea][:y_pos]
    idea.save
  end

  def destroy
    @idea = Idea.find_by_id(params[:id])
    @idea.destroy!
    redirect_to(draw_diagram_canvas_path(@diagram))
  end

  private

  def idea_params
    params.require(:idea).permit!
  end

  def set_canvas_and_diagram
    @diagram = Diagram.find_by_id(params[:diagram_id])
    @canvas = @diagram.try(:canvas)
  end


end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_edit.html.erb
<%= render partial: 'form', locals: {idea: idea, form_action: 'update'} %>

app/views/ideas/_form.html.erb
<div class="card border-dark mb-3">
  <div class="card-body">
    <h5 class="card-title">IDEA</h5>
    <p class="card-text">
    <%= form_for(idea, :url => { :action => form_action })  do |f| %>
      <div class="form-group">
        <%= f.label :label, "Label" %>
        <%= f.text_field :label, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :url, "Link (URL)" %>
        <%= f.text_field :url, class:"form-control" %>
      </div>
<!--      <div class="form-group">-->
        <%#= f.label :background_color, "Background Color", class: "control-label" %>
<!--        <div style="width: 30%;">-->
          <%#= f.color_field :background_color, class:"form-control"%>
<!--        </div>-->
<!--      </div>-->
      <div class="form-group">
        <%= f.label :text_color, "Text Color", class: "control-label" %>
        <div style="width: 30%;">
          <%= f.color_field :text_color, class:"form-control"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class:"form-control", cols: "30", rows: "3" %>
      </div>
      <%= f.submit "SAVE", class: "btn btn-primary" %>
    <% end %>

    <% if idea.persisted? %>
      <h6 style="margin-top:20px; text-align: right;">
        <%= link_to diagram_canvas_idea_path(idea.canvas.diagram, idea), method: :delete,
                    data: { confirm: "Are you sure you want to delete this idea and remove it from the canvas?"},
                    class: "text-danger" do %>
          Delete/Remove
        <% end %>
      </h6>

  <% end %>
    </p>
  </div>
</div>

app/views/ideas/edit.js.erb
$('#editIdea').fadeOut("fast", function(){
    $('#editIdea').html("<%= escape_javascript(render partial: 'edit', locals: {idea: @idea}) %>");
    $('#editIdea').fadeIn("fast");
})