config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  get '/users/' => 'users#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :diagrams do
    resource :canvas, except: [:edit, :update, :destroy] do
      get :draw
      get :preview
      resources :ideas do
        member do
          put :update_position
        end
      end
    end
  end

end

app/models/diagram.rb
# == Schema Information
#
# Table name: diagrams
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Diagram < ApplicationRecord
  # has_paper_trail
  # acts_as_paranoid

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_one :canvas, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :user_id, presence: true


end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_edit_permission, only: [:edit, :update, :destroy]

  layout "application"

  def index
    @diagrams = current_user.diagrams
  end

  def new
    @diagram = current_user.diagrams.new
  end

  def create
    @diagram = current_user.diagrams.build(diagram_params)
    @canvas = @diagram.build_canvas
    @canvas.image_url = "default"
    if @diagram.save && @canvas.save
      flash[:notice] = "Diagram created!"
      redirect_to(edit_diagram_path(id: @diagram.id))
    else
      flash[:alert] = "Diagram was not created"
      redirect_to(new_diagram_path)
    end
  end

  def edit
    @diagram = current_user.diagrams.find_by_id(params[:id])
  end

  def update
    @diagram = current_user.diagrams.find_by_id(params[:id])
    @diagram.update(diagram_params)
    return redirect_to diagrams_path
  end

  def destroy
    @diagram = current_user.diagrams.find_by_id(params[:id])
    @diagram.destroy
    return redirect_to diagrams_path
  end

  private

  def diagram_params
    params.require(:diagram).permit(:name, :description, :user_id)
  end
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/views/diagrams/edit.html.erb
<div class="" style="display: flex;">
  <div class="" style="flex: 2;">
    <div class="card" >
      <div class="card-body">
        <h2 class="card-title">Edit Diagram</h2>
        <p class="card-text">
        <%= form_for(@diagram, :url => { :action => "update" })  do |f| %>
          <div class="form-group">
            <%= f.label :name, "Diagram Name (*)" %>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control", cols: "30", rows: "7" %>
          </div>
          <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="" style="flex: 1; padding-left: 10px;">
    <div class="card" >
      <div class="card-body">
        <h2 class="card-title">Canvas</h2>
        <p class="card-text">Here are the possible actions on your canvas. While only you can draw and edit your canvas, anyone can preview your canvas by accessing the same view URL as yours.</p>
        <%= render partial: 'partials/canvas/actions_buttons', locals: {diagram: @diagram} %>
      </div>
    </div>

    <div></div>

    <div class="card" >
      <div class="card-body">
        <h2 class="card-title">Delete Diagram</h2>
        <p class="card-text"></p>
        <%= link_to diagram_path(@diagram), method: :delete,
                    data: { confirm: "Are you sure you want to delete this diagram?"},
                    class: "btn btn-xs btn-danger" do %>
          <i class="fas fa-trash-alt"></i> Delete Diagram
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/diagrams/index.html.erb
<h2> My Diagrams </h2>
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Diagram Name</th>
    <th scope="col">Description</th>
    <th scope="col" colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
    <% @diagrams.each do |diagram| %>
      <tr>
        <th scope="row"><%= diagram.id %></th>
        <td>
          <%= link_to edit_diagram_path(diagram) do %>
            <%= diagram.name %>
          <% end %>
        </td>
        <td><%= diagram.description %></td>

        <% if diagram.canvas %>
<!--          <td>-->
            <%#= link_to edit_diagram_canvas_path(diagram) do %>
<!--              <i class="fas fa-pen-square"></i> Edit Background-->
            <%# end %>
<!--          </td>-->
          <td>
            <%= link_to draw_diagram_canvas_path(diagram) do %>
              <i class="fas fa-pencil-ruler"></i> Draw
            <% end %>
          </td>
          <td>
            <%= link_to diagram_canvas_path(diagram), target: "_blank" do %>
              <i class="fas fa-eye"></i> Preview
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to new_diagram_canvas_path(diagram) do %>
              <i class="far fa-file"></i> Start Canvas
            <% end %>
          </td>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/diagrams/new.html.erb
<h2> New Diagram</h2>

<%= form_for(@diagram, :url => { :action => "create" })  do |f| %>
  <div class="form-group">
    <%= f.label :name, "Diagram Name (*)" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control", cols: "30", rows: "7" %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>