config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  get '/users/' => 'users#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :diagrams do
    resource :canvas, except: [:edit, :update, :destroy] do
      get :draw
      get :preview
      resources :ideas do
        member do
          put :update_position
        end
      end
    end
  end

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand ml-2" href="<%= root_path %>">mindmap app</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-2">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">
          <i class="fas fa-home"></i> Home <span class="sr-only">(current)</span>
        </a>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-project-diagram"></i> Diagrams
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= new_diagram_path %>">
              <i class="fas fa-plus"></i> New Diagram
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href=" <%= diagrams_path %>">
              <i class="fas fa-tasks"></i> Manage Diagrams
            </a>
          </div>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-users-cog"></i> Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= new_user_registration_path  %>">
                <i class="fas fa-user-plus"></i> Add User
              </a>
              <a class="dropdown-item" href=" <%= users_path %>">
                <i class="fas fa-users"></i> Manage Users
              </a>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class="navbar-nav mr-2 my-2 my-lg-0">
      <% if current_user %>
        <li class="nav-item ">
          <a class="nav-link" href="<%= edit_user_registration_path %>">
            <i class="fas fa-user"></i> <%= current_user.name %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=  destroy_user_session_path %>">
            <i class="fas fa-sign-out-alt"></i> Sign out
          </a>
        </li>
      <% else %>
        <li class="nav-item ">
          <a class="nav-link" href="<%= new_user_session_path %>">
            <i class="fas fa-sign-in-alt"></i> Log in
          </a>
        </li>
      <% end %>
    </ul>


<!--      <form class="form-inline">-->
<!--        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--      </form>-->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mindmap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <%= render partial: "layouts/nav" %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <div style="width: 70%; margin-left: 15%; margin-right: 15%; margin-top: 3%;">
      <div class="card" style="padding: 2%;">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/canvas.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mindmap</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>

  <script type="text/javascript">
      document.onmousemove=function(e) {
          let x = e.clientX
          let y = e.clientY
          console.log('x et y: ', `${x} et ${y}`)
      };
  </script>
</head>
<body>

  <%= render partial: "layouts/nav" %>
  <div style="margin-left:auto; margin-right:auto;">
    <%= yield %>
  </div>


</body>
</html>

app/views/layouts/workspace.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mindmap</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script type="text/javascript">
      document.onmousemove=function(e) {
          let x = e.clientX
          let y = e.clientY
          console.log('x et y: ', `${x} et ${y}`)
      };
  </script>
</head>
<body>

  <%= render partial: "layouts/nav" %>
  <div style="margin-left:auto; margin-right:auto;">
    <%= yield %>
  </div>


</body>
</html>